import type { Company } from "./types";

export const COMPANIES: Company[] = [
  {
    id: "c1",
    name: "DHL Logistics",
    status: "pending",
    country: "China",
    city: "Hejiang",
    countryCode: "CN",
    managerName: "Lee Sin",
    phone: "+86 010 5555 7890",
    numDrivers: 15,
    numActiveVehicles: 5,
    lastActivity: "2d ago",
  },
  {
    id: "c2",
    name: "PTM Transport",
    status: "active",
    country: "China",
    city: "Hejiang",
    countryCode: "CN",
    managerName: "Lee Sin",
    phone: "+86 010 5555 7890",
    numDrivers: 15,
    numActiveVehicles: 5,
    lastActivity: "2d ago",
  },
  {
    id: "c3",
    name: "UPS Logistics",
    status: "inactive",
    country: "China",
    city: "Hejiang",
    countryCode: "CN",
    managerName: "Lee Sin",
    phone: "+86 010 5555 7890",
    numDrivers: 15,
    numActiveVehicles: 5,
    lastActivity: "2d ago",
  },
  {
    id: "c4",
    name: "UPS Logistics",
    status: "inactive",
    country: "China",
    city: "Hejiang",
    countryCode: "CN",
    managerName: "Lee Sin",
    phone: "+86 010 5555 7890",
    numDrivers: 15,
    numActiveVehicles: 5,
    lastActivity: "2d ago",
  },
  {
    id: "c5",
    name: "Namous Transport",
    status: "rejected",
    country: "China",
    city: "Hejiang",
    countryCode: "CN",
    managerName: "Lee Sin",
    phone: "+86 010 5555 7890",
    numDrivers: 15,
    numActiveVehicles: 5,
    lastActivity: "2d ago",
  },
  {
    id: "c6",
    name: "UPS Logistics",
    status: "inactive",
    country: "China",
    city: "Hejiang",
    countryCode: "CN",
    managerName: "Lee Sin",
    phone: "+86 010 5555 7890",
    numDrivers: 15,
    numActiveVehicles: 5,
    lastActivity: "2d ago",
  },
];


