import type { Company } from "./types";
import comppanielogo1 from "../../assets/images/companieslogo/company1.png";
import comppanielogo2 from "../../assets/images/companieslogo/company2.png";
import comppanielogo3 from "../../assets/images/companieslogo/company3.png";
import comppanielogo4 from "../../assets/images/companieslogo/company4.png";
import comppanielogo5 from "../../assets/images/companieslogo/company5.png";
export const COMPANIES: Company[] = [
  {
    id: "c1",
    name: "DHL Logistics",
    logoUrl: comppanielogo1,
    status: "pending",
    country: "China",
    city: "Hejiang",
    countryCode: "CN",
    managerName: "Lee Sin",
    phone: "+86 010 5555 7890",
    numDrivers: 15,
    numActiveVehicles: 5,
    lastActivity: "2d ago",
  },
  {
    id: "c2",
    name: "PTM Transport",
    logoUrl: comppanielogo2,
    status: "active",
    country: "Germany",
    city: "Berlin",
    countryCode: "DE",
    managerName: "Hans Schmidt",
    phone: "+49 30 1234 5678",
    numDrivers: 28,
    numActiveVehicles: 12,
    lastActivity: "1h ago",
  },
  {
    id: "c3",
    name: "UPS Logistics",
    logoUrl: comppanielogo3,
    status: "inactive",
    country: "United States",
    city: "Atlanta",
    countryCode: "US",
    managerName: "John Miller",
    phone: "+1 404 555 1234",
    numDrivers: 42,
    numActiveVehicles: 18,
    lastActivity: "3w ago",
  },
  {
    id: "c4",
    name: "FedEx Express",
    logoUrl: comppanielogo4,
    status: "active",
    country: "France",
    city: "Paris",
    countryCode: "FR",
    managerName: "Marie Dubois",
    phone: "+33 1 42 86 82 00",
    numDrivers: 35,
    numActiveVehicles: 22,
    lastActivity: "4h ago",
  },
  {
    id: "c5",
    name: "Namous Transport",
    logoUrl: comppanielogo5,
    status: "rejected",
    country: "Spain",
    city: "Barcelona",
    countryCode: "ES",
    managerName: "Carlos Rodriguez",
    phone: "+34 93 123 4567",
    numDrivers: 8,
    numActiveVehicles: 3,
    lastActivity: "1w ago",
  },
  {
    id: "c6",
    name: "Swift Cargo",
    logoUrl: comppanielogo1,
    status: "active",
    country: "United Kingdom",
    city: "London",
    countryCode: "GB",
    managerName: "James Wilson",
    phone: "+44 20 7946 0958",
    numDrivers: 52,
    numActiveVehicles: 31,
    lastActivity: "30m ago",
  },
  {
    id: "c7",
    name: "Euro Transport Hub",
    logoUrl: comppanielogo2,
    status: "pending",
    country: "Italy",
    city: "Milan",
    countryCode: "IT",
    managerName: "Giuseppe Rossi",
    phone: "+39 02 1234 5678",
    numDrivers: 19,
    numActiveVehicles: 7,
    lastActivity: "5d ago",
  },
  {
    id: "c8",
    name: "Nordic Freight",
    logoUrl: comppanielogo3,
    status: "active",
    country: "Sweden",
    city: "Stockholm",
    countryCode: "SE",
    managerName: "Erik Andersson",
    phone: "+46 8 123 456 78",
    numDrivers: 31,
    numActiveVehicles: 16,
    lastActivity: "2h ago",
  },
  {
    id: "c9",
    name: "Atlas Shipping",
    logoUrl: comppanielogo4,
    status: "inactive",
    country: "Netherlands",
    city: "Rotterdam",
    countryCode: "NL",
    managerName: "Jan van der Berg",
    phone: "+31 10 123 4567",
    numDrivers: 24,
    numActiveVehicles: 9,
    lastActivity: "2w ago",
  },
  {
    id: "c10",
    name: "Alpine Logistics",
    logoUrl: comppanielogo5,
    status: "active",
    country: "Switzerland",
    city: "Zurich",
    countryCode: "CH",
    managerName: "Anna Müller",
    phone: "+41 44 123 45 67",
    numDrivers: 27,
    numActiveVehicles: 14,
    lastActivity: "6h ago",
  },
];


