import type { Driver } from "./types";
import driver1 from "../../assets/images/drivers/driver1.png";
import driver2 from "../../assets/images/drivers/driver2.png";
import driver3 from "../../assets/images/drivers/driver3.png";
import driver4 from "../../assets/images/drivers/driver4.png";
export const DRIVERS: Driver[] = [
  {
    id: "d1",
    name: "Ahmed Hassan",
    avatarUrl: driver1,
    status: "pending",
    country: "Egypt",
    city: "Cairo",
    countryCode: "EG",
    managerName: "Mohamed Ali",
    phone: "+20 2 5555 1234",
    numShipments: 25,
    numActiveVehicles: 3,
    lastActivity: "1d ago",
  },
  {
    id: "d2",
    name: "John Smith",
    avatarUrl: driver2,
    status: "active",
    country: "USA",
    city: "New York",
    countryCode: "US",
    managerName: "Sarah Johnson",
    phone: "+1 555 123 4567",
    numShipments: 42,
    numActiveVehicles: 5,
    lastActivity: "2h ago",
  },
  {
    id: "d3",
    name: "Maria Garcia",
    avatarUrl: driver3,
    status: "active",
    country: "Spain",
    city: "Madrid",
    countryCode: "ES",
    managerName: "Carlos Rodriguez",
    phone: "+34 91 555 7890",
    numShipments: 38,
    numActiveVehicles: 4,
    lastActivity: "4h ago",
  },
  {
    id: "d4",
    name: "Li Wei",
    avatarUrl: driver4,
    status: "inactive",
    country: "China",
    city: "Beijing",
    countryCode: "CN",
    managerName: "Wang Ming",
    phone: "+86 10 5555 9876",
    numShipments: 15,
    numActiveVehicles: 2,
    lastActivity: "1w ago",
  },
  {
    id: "d5",
    name: "Pierre Dubois",
    avatarUrl: driver1,
    status: "rejected",
    country: "France",
    city: "Paris",
    countryCode: "FR",
    managerName: "Jean Martin",
    phone: "+33 1 55 55 12 34",
    numShipments: 8,
    numActiveVehicles: 1,
    lastActivity: "3d ago",
  },
  {
    id: "d6",
    name: "Anna Kowalski",
    avatarUrl: driver2,
    status: "active",
    country: "Poland",
    city: "Warsaw",
    countryCode: "PL",
    managerName: "Piotr Nowak",
    phone: "+48 22 555 5678",
    numShipments: 31,
    numActiveVehicles: 3,
    lastActivity: "6h ago",
  },
  {
    id: "d7",
    name: "Hans Müller",
    avatarUrl: driver3,
    status: "active",
    country: "Germany",
    city: "Berlin",
    countryCode: "DE",
    managerName: "Klaus Schmidt",
    phone: "+49 30 1234 5678",
    numShipments: 47,
    numActiveVehicles: 6,
    lastActivity: "30m ago",
  },
  {
    id: "d8",
    name: "Sofia Rossi",
    avatarUrl: driver4,
    status: "pending",
    country: "Italy",
    city: "Rome",
    countryCode: "IT",
    managerName: "Giuseppe Bianchi",
    phone: "+39 06 5555 4321",
    numShipments: 19,
    numActiveVehicles: 2,
    lastActivity: "5h ago",
  },
  {
    id: "d9",
    name: "Olaf Andersen",
    avatarUrl: driver1,
    status: "active",
    country: "Norway",
    city: "Oslo",
    countryCode: "NO",
    managerName: "Erik Hansen",
    phone: "+47 22 12 34 56",
    numShipments: 35,
    numActiveVehicles: 4,
    lastActivity: "3h ago",
  },
  {
    id: "d10",
    name: "Yuki Tanaka",
    avatarUrl: driver2,
    status: "inactive",
    country: "Japan",
    city: "Tokyo",
    countryCode: "JP",
    managerName: "Hiroshi Sato",
    phone: "+81 3 5555 6789",
    numShipments: 12,
    numActiveVehicles: 1,
    lastActivity: "2w ago",
  },
];
