import type { Driver } from "./types";

export const DRIVERS: Driver[] = [
  {
    id: "d1",
    name: "Ahmed Hassan",
    status: "pending",
    country: "Egypt",
    city: "Cairo",
    countryCode: "EG",
    managerName: "Mohamed Ali",
    phone: "+20 2 5555 1234",
    numShipments: 25,
    numActiveVehicles: 3,
    lastActivity: "1d ago",
  },
  {
    id: "d2",
    name: "John Smith",
    status: "active",
    country: "USA",
    city: "New York",
    countryCode: "US",
    managerName: "Sarah Johnson",
    phone: "+1 555 123 4567",
    numShipments: 42,
    numActiveVehicles: 5,
    lastActivity: "2h ago",
  },
  {
    id: "d3",
    name: "Maria Garcia",
    status: "active",
    country: "Spain",
    city: "Madrid",
    countryCode: "ES",
    managerName: "Carlos Rodriguez",
    phone: "+34 91 555 7890",
    numShipments: 38,
    numActiveVehicles: 4,
    lastActivity: "4h ago",
  },
  {
    id: "d4",
    name: "Li Wei",
    status: "inactive",
    country: "China",
    city: "Beijing",
    countryCode: "CN",
    managerName: "Wang Ming",
    phone: "+86 10 5555 9876",
    numShipments: 15,
    numActiveVehicles: 2,
    lastActivity: "1w ago",
  },
  {
    id: "d5",
    name: "Pierre Dubois",
    status: "rejected",
    country: "France",
    city: "Paris",
    countryCode: "FR",
    managerName: "Jean Martin",
    phone: "+33 1 55 55 12 34",
    numShipments: 8,
    numActiveVehicles: 1,
    lastActivity: "3d ago",
  },
  {
    id: "d6",
    name: "Anna Kowalski",
    status: "active",
    country: "Poland",
    city: "Warsaw",
    countryCode: "PL",
    managerName: "Piotr Nowak",
    phone: "+48 22 555 5678",
    numShipments: 31,
    numActiveVehicles: 3,
    lastActivity: "6h ago",
  },
];
